spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/blogdb
    username: postgres
    password: secret

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: fal

  servlet:
    multipart:
      max-file-size: 10MB

jwt:
  secret: ${JWT_SECRET}
  expiration: 86400000

file:
  upload-dir: ./uploads